//! Operation: a single payload-bearing unit inside a [`crate::Request`].
//!
//! Under the contract-local-verb architecture, `Operation` no longer
//! carries a universal `SignalVerb` enum. The operation root *is* the
//! contract verb directly; the payload enum is generated by the
//! `signal_channel!` macro and each variant of that enum names the
//! contract-local verb (e.g. `Query`, `Submit`, `Configure`,
//! `Register`, `Observe`).
//!
//! `Operation<Payload>` therefore reduces to a transparent
//! payload-bearer. The wire codec emits the payload directly without
//! an outer verb wrapper; the payload's own NOTA encoding contributes
//! the record head that names the operation.

use nota_codec::{Decoder, Encoder, NotaDecode, NotaEncode, Result};
use rkyv::{Archive, Deserialize as RkyvDeserialize, Serialize as RkyvSerialize};

/// One contract operation in a [`crate::Request`]. Holds the payload;
/// the payload's NOTA record head names the contract-local verb.
#[derive(Archive, RkyvSerialize, RkyvDeserialize, Debug, Clone, PartialEq, Eq)]
pub struct Operation<Payload> {
    pub payload: Payload,
}

impl<Payload> Operation<Payload> {
    pub fn new(payload: Payload) -> Self {
        Self { payload }
    }

    pub fn payload(&self) -> &Payload {
        &self.payload
    }

    pub fn into_payload(self) -> Payload {
        self.payload
    }
}

/// NOTA codec: emit the payload directly. The payload (typically a
/// `signal_channel!`-generated enum) emits its own record head naming
/// the contract verb — no outer `Operation` wrapper appears in the
/// NOTA text.
impl<Payload> NotaEncode for Operation<Payload>
where
    Payload: NotaEncode,
{
    fn encode(&self, encoder: &mut Encoder) -> Result<()> {
        self.payload.encode(encoder)
    }
}

impl<Payload> NotaDecode for Operation<Payload>
where
    Payload: NotaDecode,
{
    fn decode(decoder: &mut Decoder<'_>) -> Result<Self> {
        let payload = Payload::decode(decoder)?;
        Ok(Operation { payload })
    }
}
